"""Generate a compile-time geometry table; GPIO count remains 16 on F411."""
import argparse
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
from desktop_app.array_geometry import Geometry, grid_geometry


def generate(g, path):
    g.validate()
    if len(g.elements) != 16:
        raise ValueError('F411 当前接线只支持 16 路；增加通道需要另行实现输出硬件')
    legacy = g == grid_geometry(g.rows, g.cols, g.pitch_um/1000)
    lines = ['/* Generated by generate_geometry.py; acoustic face centres, nm. */',
             '#ifndef ARRAY_GEOMETRY_H', '#define ARRAY_GEOMETRY_H', '#include <stdint.h>',
             f'#define ARRAY_ROWS {g.rows}', f'#define ARRAY_COLS {g.cols}',
             f'#define ARRAY_PITCH_UM {g.pitch_um}', f'#define ARRAY_EXPLICIT {int(not legacy)}',
             f'#define ARRAY_ID "{g.identity}"', f'#define ARRAY_SOUND_MM_S {g.sound_speed_mm_s}',
             'static const int32_t array_elements[16][6] = {']
    lines += ['    {'+', '.join(map(str, e))+'},' for e in g.elements]
    lines += ['};', '#endif', '']
    Path(path).write_text('\n'.join(lines), encoding='utf-8')


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('profile', type=Path)
    p.add_argument('--output', type=Path, default=Path(__file__).with_name('include')/'array_geometry.h')
    a = p.parse_args()
    generate(Geometry.load(a.profile), a.output)
    print(a.output)


if __name__ == '__main__':
    main()
