name: touchsee_mobile
description: "触见：BLE 触觉图形控制与无硬件演示。"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: 1.36.8
  shared_preferences: 2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
